- id: conference:IWQOS25
  type: paper
  title: "Bringing New Life to Old Tools: Measuring Source Address Validation Deployment with 6in4 Tunnels"
  authors:
  - Jiaxing Guo
  - Lin He
  - Daguo Cheng
  - Xingang Shi
  - Ying Liu
  publisher: In Proceedings of the 33rd IEEE/ACM International Symposium on Quality of Service (IWQoS 2025)
  date: '2025-07-02'
  link:
  orcid:
  plugin: orcid.py
  file: orcid.yaml
  description: TBA
  image: 
  buttons:
  - type: manubot
    link: 
  - type: source
    text: Manuscript Source
    link: 
  - type: website
    link: 
  tags:
  - SAV
  - IPv6
  - Network Measurement
  repo: 

- id: conference:IWQOS25
  type: paper
  title: "APCC: Enabling Reliable IPv6 Covert Communication with Aliased Prefixes"
  authors:
  - Zhaoan Wang
  - Lin He
  - Daguo Cheng
  - Ying Liu
  publisher: In Proceedings of the 33rd IEEE/ACM International Symposium on Quality of Service (IWQoS 2025)
  date: '2025-07-02'
  link:
  orcid:
  plugin: orcid.py
  file: orcid.yaml
  description: TBA
  image: 
  buttons:
  - type: manubot
    link: 
  - type: source
    text: Manuscript Source
    link: 
  - type: website
    link: 
  tags:
  - IPv6
  - Covert Communication
  - FRP
  - Aliased Prefixes
  repo: 


- id: conference:ATC25
  type: paper
  title: "TGW: Operating an Efficient and Resilient Cloud Gateway at Scale"
  authors:
  - Yifan Yang
  - Lin He
  - Jiasheng Zhou
  - Xiaoyi Shi
  - Yichi Xu
  - Shicheng Wang
  - Jinlong E
  - Ying Liu
  - Junwei Zhang
  - Zhuang Yuan
  - Hengyang Xu
  publisher: In Proceedings of the 2025 USENIX Annual Technical Conference (ATC)
  date: '2025-07-07'
  link:
  orcid:
  plugin: orcid.py
  file: orcid.yaml
  description: Large-scale cloud data centers have become a critical Internet infrastructure. As the cloud entrance, today's cloud gateways have integrated multiple functions such as elastic public access and load balancing to cope with the rapid growth of services and requirements. To meet the demands of large-scale clouds for efficient packet forwarding, scalable state management, and high resilience, we design, deploy, and operate Tencent Gateway (TGW), an efficient and resilient cloud gateway at scale. Compared to other large cloud providers that primarily offer services like search, e-commerce, or short-form video, the "killer services" of Tencent Cloud are online gaming and live streaming, which come with much stricter requirements for latency, jitter, and packet loss. From a technological perspective, TGW is highly decoupled and modular, with core components focused on efficient forwarding planes, a scalable state migration mechanism, a resilient failure recovery mechanism, and a failure detection and localization system. In terms of engineering, TGW has been operating in large-scale, real-world industrial environments for eight years, during which we have gained extensive insights and experience. We evaluate TGW both in testbed and real-world scenarios. In our testbed, TGW's single node achieves 2.9×the forwarding capacity of prior systems. Between clusters, states and traffic can be migrated in 4s without packet loss. In our real-world environment, TGW handles tens of Tbps of traffic, with a worst-case packet drop rate ranging from 10<sup>-7</sup> to 10<sup>-4</sup>, while balancing traffic across clusters. Additionally, TGW can quickly migrate states and traffic and recover from failures without tenant awareness, guided by our failure localization system, achieving 100% availability for years.
  image: 
  buttons:
  - type: manubot
    link: 
  - type: source
    text: Manuscript Source
    link: 
  - type: website
    link: 
  tags:
  - Cloud Gateway
  repo: 

- id: doi:10.1145/3696410.3714809
  type: paper
  title: "Miresga: Accelerating Layer-7 Load Balancing with Programmable Switches"
  authors:
  - Xiaoyi Shi
  - Lin He
  - Jiasheng Zhou
  - Yifan Yang
  - Ying Liu
  publisher: In Proceedings of Proceedings of the ACM Web Conference 2025 (WWW)
  date: '2025-04-28'
  link: https://dl.acm.org/doi/pdf/10.1145/3696410.3714809
  orcid:
  plugin: orcid.py
  file: orcid.yaml
  description: > 
    As online cloud services expand rapidly, layer-7 load balancing has become indispensable for maintaining service availability and performance. The emergence of programmable switches with both high performance and a certain degree of flexibility has made it possible to apply programmable switches to load balancing. Nevertheless, the limited memory capacity and the relatively sluggish speed of table entry insertion and deletion of programmable switches have severely constrained their performance.

    To this end, we introduce Miresga, a hybrid and high-performance layer-7 load balancing system by co-designing hardware and software. The core idea of Miresga is to maximize the utilization of hardware and software resources by rationally partitioning the layer-7 load balancing task, thereby improving performance. To achieve this, Miresga offloads the elephant flows, which account for the majority of traffic, to programmable switches that excel at packet processing, and Miresga utilizes general-purpose servers with stronger computational capabilities to parse application layer protocols and apply load balancing rules. To alleviate memory pressure on the programmable switch, Miresga employs a back-end agent to handle memory-intensive tasks, working in conjunction with the programmable switch to complete the offloaded tasks. This design leverages the performance advantages of the programmable switch while avoiding bottlenecks caused by its limited memory and table insertion speed. We implement the Miresga prototype with a 3.2 Tbps Intel Tofino switch and general-purpose servers. The evaluation results show that Miresga achieves 3.9× throughput and 0.4× latency compared to software load balancing solutions. Compared to the state-of-the-art design employing programmable switches, Miresga achieves almost the same throughput and latency for delivering large objects and 5.0× throughput and 0.2× latency when transmitting small objects.
  image:
  buttons:
  - type: manubot
    link: 
  - type: source
    text: Manuscript Source
    link: https://dl.acm.org/doi/pdf/10.1145/3696410.3714809
  - type: website
    link: https://dl.acm.org/doi/10.1145/3696410.3714809
  tags:
  - SDN
  - Layer-7 Load Balancing
  - Programmable Switch
  repo: "https://github.com/THUNAME/Miresga"

- id: conference:INFOCOM25
  type: paper
  title: "6Map: Enabling Fast Active IPv6 Address Discovery with Programmable Switches"
  authors:
  - Jiasheng Zhou
  - Lin He
  - Yifan Yang
  - Xiaoyi Shi
  - Daguo Cheng
  - Jinlong E
  - Ying Liu
  - Dong Zhang
  publisher: In Proceedings of the 44th IEEE Conference on Computer Communications (INFOCOM)
  date: '2025-05-19'
  link: 
  orcid: 
  plugin: orcid.py
  file: orcid.yaml
  description: The vast address space of IPv6 makes it impractical to apply exhaustive scanning to survey the entire network. Existing studies that aim to quickly discover active IPv6 addresses by optimizing the scanning space face issues of poor scalability and high time complexity, which hinder a comprehensive understanding of the IPv6 network and impede the timely provision of security snapshots and the development of IPv6. Fortunately, the emergence of programmable switches provides an opportunity to address the above issues. To this end, we propose 6Map, a fast active IPv6 address discovery system based on programmable switches. We design a lightweight target generation algorithm running on the control plane of the programmable switch and implement fast scanning address generation on the switch ASIC. The experimental results show that IPv6 active address discovery efficiency is up to 40.1× compared to the state-of-the-art method at the 100M probe budget.
  image: 
  buttons:
  - type: manubot
    link: 
  - type: source
    text: Manuscript Source
    link: 
  - type: website
    link: 
  tags:
  - SDN
  - IPv6
  - Active Address Discovery
  - Programmable Switch
  repo: 


- id: doi:10.1109/ICNP61940.2024.10858548
  title: "Luori: Active Probing and Evaluation of Internet-wide IPv6 Fully Responsive Prefixes"
  authors:
  - Daguo Cheng
  - Lin He
  - Chentian Wei
  - Qilei Yin
  - Boran Jin
  - Zhaoan Wang
  - Xiaoteng Pan
  - Sixu Zhou
  - Ying Liu
  - Shenglin Zhang
  - Fuchao Tan
  - Wenmao Liu
  link: https://ieeexplore.ieee.org/document/10858548
  publisher: "Proceedings of the 32nd IEEE International Conference on Network Protocols (ICNP)"
  year: "2024"
  address: Charleroi, Belgium
  date: "2024-10-28"
  description: "With the large-scale deployment and application of IPv6, IPv6 network measurements will become increasingly important. However, a special type of IPv6 prefix called Fully Responsive Prefix (FRP) is having a significant impact on IPv6 measurement campaigns, which is defined as all addresses under a prefix responding to scans. Obviously, there cannot be a real responder behind each of these addresses. To reveal the current status and impact of Internet-wide IPv6 FRPs, we propose for the first time an active probing method for Internet-wide IPv6 FRPs, Luori, which transforms the active probing process under IPv6 huge prefix space (potential range of prefix presence) into a dynamic search process in a tree based on reinforcement learning, achieving efficient probing of arbitrary routing prefixes. The evaluation results show that Luori found 31.7K largest FRPs in a single Internet-wide probing with 11M budget, covering 1.5×1030 address space, which is 106× that of existing methods. More importantly, after six months of Internet-wide probing, we have found 516K largest FRPs, which covers 1.3 × 1033 address space and 795 ASes, making it the largest publicly known FRP list. Based on this list, we screen out 20% of the addresses covered by FRPs from a well-known IPv6 active address dataset. Furthermore, we further analyze and find that the distribution of these FRPs is extensive and their implementation methods are diverse, which can provide beneficial references for the practical application of FRPs. We also make this list publicly available and maintain it long-term for use and study by relevant researchers."
  tags:
  - IPv6
  - Network Measurement
  - Fully Responsive Prefixes
  - Active Probing
  - Reinforcement Learning




- id: doi:10.1145/3651890.3672230
  title: "P4runpro: Enabling Runtime Programmability for RMT Programmable Switches"
  authors:
  - Yifan Yang
  - Lin He
  - Jiasheng Zhou
  - Xiaoyi Shi
  - Jiamin Cao
  - Ying Liu
  publisher: In Proceedings of the 2024 Annual Conference of the ACM Special Interest Group on Data Communication (SIGCOMM)
  date: '2024-08-04'
  link: https://dl.acm.org/doi/pdf/10.1145/3651890.3672230
  orcid: 
  plugin: orcid.py
  file: orcid.yaml
  type: paper
  description: Programmable switches have revolutionized network operations by enabling the flexible customization of packet processing logic using language like P4. However, changing the programs running on the switch requires disturbing traffic and suspending other unrelated programs. In this paper, we present P4runpro, enabling runtime data plane updates with dynamic resource allocation. The P4runpro data plane abstracts hardware resources and defines dynamically reconfigurable atomic operations that form packet processing logic. P4runpro provides runtime programming interfaces called P4runpro primitives for the operator to write high-level programs. We have designed the P4runpro compiler to automatically and consistently link the P4runpro programs to the running data plane. We implement our prototype on a Tofino switch. We implement 15 example runtime programs using P4runpro to demonstrate its generality and expressiveness. Our evaluation results show that compared to the state-of-the-art, P4runpro can respond within hundreds of milliseconds, achieve an average of 60% to 80% dynamic resource utilization, concurrently run ≈0.6K to ≈2.8K programs, and introduce lower overhead. Our case studies illustrate the benefit of runtime programming and prove the same functionality between P4runpro and conventional P4 programs.
  image: 
  buttons:
  - type: manubot
    link: 
  - type: source
    text: Manuscript Source
    link: https://dl.acm.org/doi/pdf/10.1145/3651890.3672230
  - type: website
    link: https://dl.acm.org/doi/10.1145/3651890.3672230
  tags:
  - SDN
  - Programmable Switches
  - P4
  - Runtime Programmability
  repo: https://github.com/P4runpro/P4runpro





- id: doi:10.1109/IPCCC59868.2024.10850165
  title: "Overlooked Backdoors: Investigating 6to4 Tunnel Nodes and Their Exploitation in the Wild"
  authors:
  - Jiaxing Guo
  - Lin He
  - Ying Liu
  link: https://ieeexplore.ieee.org/document/10850165
  publisher: "Proceedings of the 43rd IEEE International Performance Computing and Communications Conference (IPCCC)"
  year: "2024"
  address: Orlando, Florida, USA
  date: "2024-11-22"
  description: "As native IPv6 adoption increases, the use of 6to4 tunnels has declined, yet they remain a significant security concern in today's Internet. This study investigates the real-world deployment of 6to4 tunnels, revealing their current scale, characteristics, and security implications. We identify open 6to4 relays in 216 countries and 13,114 autonomous systems, noting stable short-term counts but a long-term decline. We analyze the security of these nodes and find over 578k nodes vulnerable to address spoofing and packet injection. Additionally, we present several under-emphasized scenarios where open 6to4 nodes are abused, including leveraging services on 6to4 nodes as traffic amplifiers, circumventing restrictions using multiple 6to4 addresses, and connecting 6to4 nodes to render attacks untraceable."
  tags:
  - IPv6
  - 6to4 Tunnels
  - Security
  - Address Spoofing

  

